### PR TITLE
Fix broken sass path

### PR DESCRIPTION
**Pull request by mthjones**
I'm not entirely sure this is necessary and I may have my SASS set up incorrectly, but in order to get this working with fra-manager, I had to change this path.

### CODE REVIEW

**Comment by dbatiste** [comment]
Thanks Matt.  Good catch.

**Comment by dbatiste** [comment]
Looking at this again... I don't think you should be relying on this .scss file from your FRA.  The CSS gets generated and published, and the React component relies on the "app-error" class name.  So, I think you need to include that published CSS in your FRA.

**Comment by dbatiste** [comment]
If you want to reference the .scss, then I think .npmignore will need to be updated.

**Comment by mthjones** [comment]
Currently I'm [importing the SCSS file](https://github.com/Brightspace/fra-manager/blob/master/src/app.scss#L4), which (imo) makes a lot more sense when working with SCSS with the ablity to actually import stuff and then have it built into a single app file.

There's no way (AFAIK) to import a plain CSS file into SCSS like there is with LESS.

**Comment by dbatiste** [comment]
Yeah ok... that's cool.  I think .npmignore should be updated too though.

**Comment by mthjones** [comment]
I think this should actually be closed for now until we figure out a better solution. Apparently the `node_modules` path works on some machines (mine) and breaks on others (everyone else's). @dlockhart and I were discussing some possible alternatives, but for now I can continue pointing `fra-manager` to my fork.

**Pull request closed without merging**
